### ISSUE TITLE
Сделать валидацию для инпутов на странице студента

### ISSUE THREAD

**Issue by perpl777** [perpl777/college-portfolio-frontend#11]
Валидации 
Для файла: не более 5мб
Фото до 2-5 МБ
0т 1500х1500 до 2500х2500
Проверить разрешение
Инпут тайтл <40
Инпут описание <500
surname: <30
name: <30
patronymic?: <30
specialization: string
technologies: string
about_info: <200
url_github?: ссылка <50
url_behance?: ссылка <50
url_vk?: ссылка <50
url_photo: ссылка  <50

**Comment by Evangel57** [comment]
кто будет тестировать, посмотрите все инпуты на сайте, попробуйте невалидные данные покидать

**Comment by Evangel57** [comment]
Файл в беседе с резальтатами тестирования

**Comment by perpl777** [comment]
при редактировании постов или студента нужно сделать чтобы не нужно было менять всё данные

**Comment by perpl777** [comment]
Сделать, чтобы разрешалось выкладывать посты без фото

**Comment by Evangel57** [comment]
Сделано, нужно будет протестировать не только данными но и верстку инпут формочек на разных разрешениях
