### ISSUE TITLE
Исправление ошибок по верстке

### ISSUE THREAD

**Issue by Evangel57** [perpl777/college-portfolio-frontend#20]
Сделать, чтобы дизайн этих выборов был минималистичнее, подходил бы к сайту. Чтобы выбор технологий тоже был выпадающим списком

![Image](https://github.com/user-attachments/assets/ad3f1a35-80e5-4885-b9a1-8596d2f02ce3)

Компонент для этого уже существует

**Comment by Evangel57** [comment]
Исправить

![Image](https://github.com/user-attachments/assets/242a39e6-20b6-4b21-a8c4-5d3c6a8d7961)

**Comment by Evangel57** [comment]
Добавить фильтр работ в профиле студента
![Image](https://github.com/user-attachments/assets/b3b5319e-1ab0-4df7-8b04-44aa4ccbf076)

**Comment by Evangel57** [comment]
Сделать, чтобы при нажатии на галочку у фото появлялся фон как у диплома

![Image](https://github.com/user-attachments/assets/1ef8f154-6434-496d-8dd0-5292d334c46d)

**Comment by perpl777** [comment]
На страницах с добавлением фото если фото большое то закрывает инпут

**Comment by TShuri** [comment]
> Сделать, чтобы дизайн этих выборов был минималистичнее, подходил бы к сайту. Чтобы выбор технологий тоже был выпадающим списком
> 
> ![Image](https://github.com/user-attachments/assets/ad3f1a35-80e5-4885-b9a1-8596d2f02ce3)
> 
> Компонент для этого уже существует

Не понял, где это находится и где существует компонент. Нужны пояснения)

**Comment by TShuri** [comment]
> Исправить
> 
> ![Image](https://github.com/user-attachments/assets/242a39e6-20b6-4b21-a8c4-5d3c6a8d7961)

Раздел Технологии маленький при отсутствии технологий. Если задать студенту технологии, они отображаются и отступы уже нормальные. Как вариант исправить карточку студента, чтобы отступы брались по заголовкам, а не по переданным в них значения

**Comment by Evangel57** [comment]
При переходе на страницу работы фото растягивается. сделать так, чтобы помещалось в экран

![Image](https://github.com/user-attachments/assets/b62e0d9f-485d-4628-8240-9ef0888b3387)

**Comment by Evangel57** [comment]
> > Исправить
> > ![Image](https://github.com/user-attachments/assets/242a39e6-20b6-4b21-a8c4-5d3c6a8d7961)
> 
> Раздел Технологии маленький при отсутствии технологий. Если задать студенту технологии, они отображаются и отступы уже нормальные. Как вариант исправить карточку студента, чтобы отступы брались по заголовкам, а не по переданным в них значения

Подходит. Скорее всего студент будет обязан задать технологии, но на всякий случай, пусть отступы всегда будут корректные

**Comment by Evangel57** [comment]
> > Сделать, чтобы дизайн этих выборов был минималистичнее, подходил бы к сайту. Чтобы выбор технологий тоже был выпадающим списком
> > ![Image](https://github.com/user-attachments/assets/ad3f1a35-80e5-4885-b9a1-8596d2f02ce3)
> > Компонент для этого уже существует
> 
> Не понял, где это находится и где существует компонент. Нужны пояснения)

Заполнение своего профиля. То есть нужно войти
![Image](https://github.com/user-attachments/assets/25d7a5d9-1db6-443a-b217-c21245165972)

и заполнить информацию о себе

**Comment by Evangel57** [comment]
Я вроде бы это поправляла, но тут осталось. Нужно, чтобы в регистрации осталось 2 поля. Если для стрепи необходимо 3, то попробовать вместо имени использовать почту 
![Image](https://github.com/user-attachments/assets/549d6596-2918-42d2-8057-6ecdcd0e5bf1)

**Comment by Evangel57** [comment]
Главная страница. При нажатии на галочку ошибка
![Image](https://github.com/user-attachments/assets/993febfc-7f43-449c-9b74-dc8a1684e035)

**Comment by Evangel57** [comment]
Страница студентов
Сейчас ссылка только на имени студента. Предлагаю добавить переход по onClick на всю строку

![Image](https://github.com/user-attachments/assets/8cee4150-1c82-4e76-9ec8-5ac18becb035)

**Comment by Evangel57** [comment]
Сделать красный цвет синим
![Image](https://github.com/user-attachments/assets/7a9a963f-9c96-443c-8086-2460e7d54a1c)

**Comment by TShuri** [comment]
На странице редактирования своего поста, не подгружаются данные о типе работы и теги

![Image](https://github.com/user-attachments/assets/80db72a3-7ccd-431d-9593-6b3575c0079b)

**Comment by TShuri** [comment]
# Еще не корректно подгружаются данные ФИО

ФИО подгружаются, но в полях они как подсказки, соответственно при попытке отправить форму, просит заполнить ФИО

![Image](https://github.com/user-attachments/assets/80b784fc-003c-4f41-83c5-3910c1bb827f)

**Comment by TShuri** [comment]
# Описание тоже некорректно подгружается
Описание в виде подсказки и тоже просит заполнить данные при отпраке

**Comment by TShuri** [comment]
# Кнопка "Сохранить" Не работает!. Данные не уходят

**Comment by Evangel57** [comment]
Это поправлено в другом тикете, переношу в тест
