### ISSUE TITLE
Проблемы на странице статистика

### ISSUE THREAD

**Issue by perpl777** [perpl777/college-portfolio-frontend#31]
Сейчас при нажатии на студента кидает на несуществующую страницу. Надо сделать так, чтобы либо кидалось на его страницу, либо в модальнике выводился конкретно его график

![Image](https://github.com/user-attachments/assets/dd214606-5383-4a19-b5b0-39f1c19ae70b)

**Comment by perpl777** [comment]
пока убрать лучше тогда

**Comment by Evangel57** [comment]
Пусть будет переход. Это смежная задача с

**Comment by Evangel57** [comment]
Фикс в задаче Саши, но появились проблемы с некоторыми студентами

**Comment by perpl777** [comment]
у меня вроде норм
