### ISSUE TITLE
баг в регистрации

### ISSUE THREAD

**Issue by perpl777** [perpl777/college-portfolio-frontend#71]
если ты регистрируешься, но данные подставляются автоматически, они не считываются

**Comment by Evangel57** [comment]
я не могу зайти в регистрацию, меня выкидывает из модальника, но я тоже помню этот баг. Я посмотрела в логине все ок, даже если подставляются, а в регистрации идентичный код. странно

**Comment by TShuri** [comment]
# После нажатия на кнопку "Зарегистрироваться, кидает на пустую страницу myprofile, без id
