### ISSUE TITLE
Исправление валидации

### ISSUE THREAD

**Issue by TShuri** [perpl777/college-portfolio-frontend#97]
- [ ] Убрать валидацию по пикселям у фото
> "чел по дизайну сказал, что так лучше не делать"
- [ ] Сделать, чтобы отчество было обязательным полем

**Comment by Evangel57** [comment]
предлагаю сделать минимальное по пикселям и
максимальное валидировать тогда по весу

например минимальное 500 на 500, максимальное 15мб
проверить, чтобы на мобилке работало. Сейчас есть баг, на мобилке не дает добавить фото 640 на 640. Возможно фото сжимается или типа того

**Comment by Evangel57** [comment]
про отчество
В бд
в создании и редактировании валидация
